-- MySQL Script generated by MySQL Workbench
-- Tue May 23 09:54:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_sistema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_sistema`;

-- -----------------------------------------------------
-- Schema bd_sistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_sistema` DEFAULT CHARACTER SET utf8 ;
USE `bd_sistema` ;

-- -----------------------------------------------------
-- Table `bd_sistema`.`chefe_conselho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sistema`.`chefe_conselho` ;

CREATE TABLE IF NOT EXISTS `bd_sistema`.`chefe_conselho` (
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema`.`login_comunidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sistema`.`login_comunidade` ;

CREATE TABLE IF NOT EXISTS `bd_sistema`.`login_comunidade` (
  `idlogin` INT NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `chefe_conselho_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlogin`),
    FOREIGN KEY (`chefe_conselho_cpf`)
    REFERENCES `bd_sistema`.`chefe_conselho` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema`.`comunidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sistema`.`comunidade` ;

CREATE TABLE IF NOT EXISTS `bd_sistema`.`comunidade` (
  `idComunidade` INT NOT NULL AUTO_INCREMENT,
  `padroeiro` VARCHAR(45) NOT NULL,
  `localizacao` VARCHAR(45) NOT NULL,
  `chefe_conselho_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idComunidade`),
    FOREIGN KEY (`chefe_conselho_cpf`)
    REFERENCES `bd_sistema`.`chefe_conselho` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema`.`membro_conselho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sistema`.`membro_conselho` ;

CREATE TABLE IF NOT EXISTS `bd_sistema`.`membro_conselho` (
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  `idcomunidade` INT NOT NULL,
  PRIMARY KEY (`cpf`),
    FOREIGN KEY (`idcomunidade`)
    REFERENCES `bd_sistema`.`comunidade` (`idComunidade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema`.`avisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sistema`.`avisos` ;

CREATE TABLE IF NOT EXISTS `bd_sistema`.`avisos` (
  `titulo` VARCHAR(45) NOT NULL,
  `idavisos` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idavisos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema`.`avisos_comunidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sistema`.`avisos_comunidade` ;

CREATE TABLE IF NOT EXISTS `bd_sistema`.`avisos_comunidade` (
  `avisos_idavisos` VARCHAR(45) NOT NULL,
  `membro_conselho_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`avisos_idavisos`, `membro_conselho_cpf`),
    FOREIGN KEY (`avisos_idavisos`)
    REFERENCES `bd_sistema`.`avisos` (`idavisos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (`membro_conselho_cpf`)
    REFERENCES `bd_sistema`.`membro_conselho` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema`.`chefe_familia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sistema`.`chefe_familia` ;

CREATE TABLE IF NOT EXISTS `bd_sistema`.`chefe_familia` (
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema`.`PagDizimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sistema`.`PagDizimo` ;

CREATE TABLE IF NOT EXISTS `bd_sistema`.`PagDizimo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10) NOT NULL,
  `dataVencimento` DATE NOT NULL,
  `ano` INT NOT NULL,
  `chefe_familia_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`chefe_familia_cpf`)
    REFERENCES `bd_sistema`.`chefe_familia` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema`.`PagCM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sistema`.`PagCM` ;

CREATE TABLE IF NOT EXISTS `bd_sistema`.`PagCM` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10) NOT NULL,
  `dataVencimento` DATE NOT NULL,
  `mes` VARCHAR(45) NOT NULL,
  `chefe_familia_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`chefe_familia_cpf`)
    REFERENCES `bd_sistema`.`chefe_familia` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema`.`login_familia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sistema`.`login_familia` ;

CREATE TABLE IF NOT EXISTS `bd_sistema`.`login_familia` (
  `idlogin` INT NOT NULL,
  `senha` INT NOT NULL,
  `chefe_familia_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlogin`),
    FOREIGN KEY (`chefe_familia_cpf`)
    REFERENCES `bd_sistema`.`chefe_familia` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema`.`familia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sistema`.`familia` ;

CREATE TABLE IF NOT EXISTS `bd_sistema`.`familia` (
  `idFamilia` INT NOT NULL,
  `chefe_familia_cpf` VARCHAR(45) NOT NULL,
  `idComunidade` INT NOT NULL,
  PRIMARY KEY (`idFamilia`),
    FOREIGN KEY (`idComunidade`)
    REFERENCES `bd_sistema`.`comunidade` (`idComunidade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (`chefe_familia_cpf`)
    REFERENCES `bd_sistema`.`chefe_familia` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema`.`membro_familia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sistema`.`membro_familia` ;

CREATE TABLE IF NOT EXISTS `bd_sistema`.`membro_familia` (
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idfamilia` INT NOT NULL,
  PRIMARY KEY (`cpf`),
    FOREIGN KEY (`idfamilia`)
    REFERENCES `bd_sistema`.`familia` (`idFamilia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
