-- MySQL Script generated by MySQL Workbench
-- Tue May 23 07:24:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd-igreja` DEFAULT CHARACTER SET utf8 ;
USE `bd-igreja`;

-- -----------------------------------------------------
-- Table `mydb`.`chefe-conselho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-igreja`.`chefe-conselho` (
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comunidade`
-- -----------------------------------------------------
CREATE TABLE  `bd-igreja`.`comunidade` (
  `idComunidade` INT NOT NULL AUTO_INCREMENT,
  `padroeiro` VARCHAR(45) NOT NULL,
  `localizacao` VARCHAR(45) NOT NULL,
  `chefe-conselho_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idComunidade`),
    FOREIGN KEY (`chefe-conselho_cpf`)
    REFERENCES `bd-igreja`.`chefe-conselho` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chefe-familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-igreja`.`chefe-familia` (
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-igreja`.`familia` (
  `idFamilia` INT NOT NULL,
  `chefe-familia_cpf` VARCHAR(45) NOT NULL,
  `idComunidade` INT NOT NULL,
  PRIMARY KEY (`idFamilia`),
    FOREIGN KEY (`idComunidade`)
    REFERENCES `bd-igreja`.`comunidade` (`idComunidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`chefe-familia_cpf`)
    REFERENCES `bd-igreja`.`chefe-familia` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`membro-conselho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-igreja`.`membro-conselho` (
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  `idcomunidade` INT NOT NULL,
  PRIMARY KEY (`cpf`),
    FOREIGN KEY (`idcomunidade`)
    REFERENCES `bd-igreja`.`comunidade` (`idComunidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`membro-familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-igreja`.`membro-familia` (
  `idfamilia` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`),
    FOREIGN KEY (`idfamilia`)
    REFERENCES `bd-igreja`.`familia` (`idFamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login-familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-igreja`.`login-familia` (
  `idlogin` INT NOT NULL,
  `senha` INT NOT NULL,
  `chefe-familia_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlogin`),
    FOREIGN KEY (`chefe-familia_cpf`)
    REFERENCES `bd-igreja`.`chefe-familia` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login-comunidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-igreja`.`login-comunidade` (
  `idlogin` INT NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `chefe-conselho_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlogin`),
    FOREIGN KEY (`chefe-conselho_cpf`)
    REFERENCES `bd-igreja`.`chefe-conselho` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PagDizimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-igreja`.`PagDizimo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10) NOT NULL,
  `dataVencimento` DATE NOT NULL,
  `ano` INT NOT NULL,
  `chefe-familia_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`chefe-familia_cpf`)
    REFERENCES `bd-igreja`.`chefe-familia` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-igreja`.`avisos` (
  `idavisos` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idavisos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avisos_has_membro-conselho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-igreja`.`avisos_comunidade` (
  `avisos_idavisos` VARCHAR(45) NOT NULL,
  `membro-conselho_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`avisos_idavisos`, `membro-conselho_cpf`),
    FOREIGN KEY (`avisos_idavisos`)
    REFERENCES `mydb`.`avisos` (`idavisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avisos_has_membro-conselho_membro-conselho1`
    FOREIGN KEY (`membro-conselho_cpf`)
    REFERENCES `bd-igreja`.`membro-conselho` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PagCM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-igreja`.`PagCM` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10) NOT NULL,
  `dataVencimento` DATE NOT NULL,
  `mes` VARCHAR(45) NOT NULL,
  `chefe-familia_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`chefe-familia_cpf`)
    REFERENCES `bd-igreja`.`chefe-familia` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


select * from `avisos`;
select * from `avisos_comunidade`;
select * from `chefe-conselho`;
select * from `chefe-familia`;
select * from `comunidade`;
select * from `familia`;
select * from `login-comunidade`;
select * from `login-familia`;
select * from `membro-conselho`;
select * from `membro-familia`;
select * from `pagcm`;
select * from `pagdizimo`;